### ISSUE TITLE
MigPlan Wizard : Storage Class warning not shown 

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/mig-ui#707] opened 2020-03-02 17:52 UTC
Issue : 

The warning about unsupported Access Modes in PVCs is not shown in the UI. 

It takes a while until the Warning is added as a Condition in the MigPlan. The UI seems to be validating the MigPlan before the Warning is added to conditions. As a result, a user does not see the warning in MigPlan Wizard on the last step. If you open (edit) the same MigPlan again after some time, you will see the warning.  

Expected Behaviour : 

The user should see the warning on the last step before MigPlan is validated in the Wizard.

**Comment by jwmatthews** [comment] 2020-03-03 18:19
This issue impacts Summit 2020 Lab we are preparing.
If possible would be desired to fix and get into a z-stream for 1.1 before end of March.

**Comment by ibolton336** [comment] 2020-03-03 23:29
I am unable to reproduce this @pranavgaikwad - I saw the loading spinner & the warning was shown. I never saw a ready condition. 
![image](https://user-images.githubusercontent.com/11218376/75829710-ef47a800-5d7c-11ea-854e-e59bb7637546.png)

**Comment by sseago** [comment] 2020-03-03 23:33
I suspect the bug will only show up inconsistently. If the controller gets to the reconcile before the final page load, you'll see the warning. Otherwise you may not. Also, because this is only a warning, it won't impact the plan ready condition.

**Comment by ibolton336** [comment] 2020-03-03 23:53
> I suspect the bug will only show up inconsistently. If the controller gets to the reconcile before the final page load, you'll see the warning. Otherwise you may not. Also, because this is only a warning, it won't impact the plan ready condition.

On the final page, we are actually updating the migplan with all of the values from the wizard via a patch request. Once that is successful, we start polling the plan by doing a get request every n seconds. During my testing, I am unable to reproduce this. When the get request comes back, the warning condition is present on the migplan. However, I don't doubt that there could be an edge case where the controller has not completed reconciling. 


Is this a scenario where we can leverage the observedGeneration work to ensure the reconcile cycle has completed ? Has that work been finalized? @sseago

**Comment by pranavgaikwad** [comment] 2020-03-04 12:00
@ibolton336 I can reproduce this on my cluster consistently. 

The first time when I create a new plan : 

![rec](https://user-images.githubusercontent.com/9839757/75875957-c0641d00-5de2-11ea-84df-6b3c72389141.gif)

When I open the plan after some time : 

![wiz](https://user-images.githubusercontent.com/9839757/75876092-0325f500-5de3-11ea-9bc3-b1cc71107c4d.gif)

**Comment by ibolton336** [comment] 2020-03-04 20:51
I am unable to reproduce this within my environment @pranavgaikwad @sseago 
![unable-to-reproduce](https://user-images.githubusercontent.com/11218376/75921817-ccc29700-5e2f-11ea-882f-f34dcc5d2064.gif) 

I think the issue @pranavgaikwad is seeing relates to https://github.com/konveyor/mig-controller/issues/440 as I was unable to complete pv discovery using Pranavs clusters.

**Comment by ibolton336** [comment] 2020-05-12 15:22
Closed via #851

**Closed by ibolton336** 2020-05-12 15:22 UTC
Labels: bug, release-1.2.0
