### ISSUE TITLE
Add table sorting and filtering to the namespaces table

### ISSUE THREAD

**Issue by vconzola** [konveyor/mig-ui#772] opened 2020-03-25 18:36 UTC
In step 2 of the mig plan wizard we display a table of namespaces (projects) discovered on the source cluster. This table can be huge (100s or 1000s of rows), so the ability to sort/filter the content is needed.

**Comment by vconzola** [comment] 2020-03-25 18:37
Related to issue: https://github.com/fusor/mig-ui/issues/426

**Comment by eriknelson** [comment] 2020-03-26 18:51
This came up during today's labs and I'm sure will come out of summit demos. We really need to add this support sooner rather than later.

**Comment by mturley** [comment] 2020-05-28 13:20
Duplicate of https://github.com/konveyor/mig-ui/issues/794
Was resolved by https://github.com/konveyor/mig-ui/pull/803

**Closed by mturley** 2020-05-28 13:20 UTC
Labels: enhancement, needs-ux-design, sprint-candidate
